// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `transcode` plugin's OWN CUE schema — the typed plugin_input for the
// `transcode` pipeline check verb (the nested-capture cutover A pipeline word). It
// is the SINGLE SOURCE for this plugin's params, used two ways (the same contract
// core `spec` and the record/spice plugins use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the cue:gen
//     pipeline, which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a
//     TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over the
//     Describe channel; the host splices it onto the base (base ++ plugin) and
//     validates every authored `transcode:` pipeline word's plugin_input against
//     #TranscodeInput.
//
// Since the schema-compaction cutover the per-verb fields LEFT core #Op: an
// authored `transcode: <scalar>` step (scalar sugar via the declared primary
// field `to`) or `transcode: {to: mp4, artifact: …}` (map form) desugars to the
// INTERNAL plugin/plugin_input envelope, and every transcode-exclusive modifier
// lives HERE. The shared assertion matchers (exit_status/stdout/stderr) and the
// general `timeout` stay on core #Op, read off the step Op by the provider and
// self-evaluated against the ffmpeg run (R3 — the shared matcher engine).
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (base ++ plugin
// is a def-name collision check, not a base-reference resolver).
type TranscodeInput struct {
	// source_artifact — the HOST path of the source to transcode (the MJPEG the
	// capture session flushed). The bed-runner evidence phase threads the entry's
	// primary artifact here; a direct/plan-step dispatch may set it explicitly.
	// Empty → the provider falls back to the check env's source_artifact.
	SourceArtifact string `json:"source_artifact,omitempty"`

	// to — the CONTAINER FORMAT to transcode the source to. Single-purpose verb:
	// only "mp4" is supported (the default; an empty/omitted value means mp4). The
	// transcode is H.264 + yuv420p in an MP4 container, so the artifact plays
	// everywhere (the ffmpeg argv: -c:v libx264 -pix_fmt yuv420p).
	To string `json:"to,omitempty"`

	// artifact — the HOST path the transcoded file is written to. Empty (the
	// common case) → derived from the source path by swapping its extension to
	// ".mp4" (the source MJPEG the capture session flushed is already host-side).
	Artifact string `json:"artifact,omitempty"`

	// artifact_min_bytes — the post-transcode artifact-reality assertion: the
	// output MP4 must be at least this many bytes (sdk.RunArtifactValidators,
	// shared implementation).
	ArtifactMinBytes int `json:"artifact_min_bytes,omitempty"`

	// artifact_not_uniform — the SOURCE-frame motion assertion (the RDD-3 binding
	// of the nested-capture plan): evaluated on the SOURCE MJPEG frames (the
	// pre-encode JPEGs), NEVER on the transcoded output — exact hashes of
	// transcoded frames are vacuous (x264 QP noise). The provider splits the
	// source MJPEG stream into its constituent JPEGs, decodes a stream-wide
	// sample, and requires at least two distinct frame signatures: identical
	// frames FAIL honestly (a real capture shows motion), differing frames PASS.
	ArtifactNotUniform bool `json:"artifact_not_uniform,omitempty"`
}
